import type { AppProps } from 'next/app'
import Head from 'next/head'

import { ChakraProvider } from '@chakra-ui/react'
import { EthereumProvider } from '../context/EthereumContext'

import theme from "./theme"

declare global {
  interface Window { ethereum: any }
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider theme={theme}>
      <EthereumProvider>
        <Head>
          <title>Old Salt</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </EthereumProvider>
    </ChakraProvider>
  )
}

export default MyApp
