import type { NextPage } from 'next'
import React, { useContext, useState } from "react";
import Head from 'next/head';

import Footer from './Footer';
import Home from './home/Home';
import Landing from './Landing';
import Navbar from './navbar/Navbar';

import { ChakraProvider } from '@chakra-ui/react'

import { EthereumContext } from '../context/EthereumContext'

import styles from '../styles/Main.module.css';

const OldSalt: NextPage = () => {
  const { currentAccount } = useContext(EthereumContext);

  const [txInProgress, setTxInProgress] = useState<boolean>(false);

  return (
    <ChakraProvider>
      <div className={styles.view}>
        <Head>
          <title>Old Salt</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar currentAccount={currentAccount} txInProgress={txInProgress} />

        <main className={styles.main}>
          {currentAccount ?
            <Home setTxInProgress={setTxInProgress} />
          : <Landing />
          }
        </main>
      </div>
      <Footer />
    </ChakraProvider>
  )
}

export default OldSalt
