import type { NextPage } from 'next'
import React, { useCallback, useContext, useEffect, useState } from "react";
import Head from 'next/head';
import Image from 'next/image';

import styles from '../styles/Main.module.css';

import Footer from './Footer';
import Home from './home/Home';
import Landing from './Landing';
import Navbar from './navbar/Navbar';

import { EthereumContext } from '../context/EthereumContext'

const OldSalt: NextPage = () => {
  const { buildKeel, currentAccount, keels, userInventory } = useContext(EthereumContext);

  const [userKeels, setUserKeels] = useState<string[]>([]);
  const [userShips, setUserShips] = useState<string[]>([])

  const fetchKeels = useCallback(async (account) => {
    let response = await keels(account);
    //response = await response.json();
    console.log("RESP", response);

    setUserKeels(response);
  }, [currentAccount])

  useEffect(() => {
    if (currentAccount == undefined) return;
    //if (contract == undefined) return;

    fetchKeels(currentAccount);
    userInventory(currentAccount);
  }, [currentAccount])

  return (
    <>
      <div className={styles.view}>
        <Head>
          <title>Old Salt</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar currentAccount={currentAccount} />

        <main className={styles.main}>
          {currentAccount ?
            <Home 
              buildShip={() => {}}
              currentAccount={currentAccount}
              userShips={userShips} 
            />
          : <Landing />
          }
        </main>
      </div>
      <Footer />
    </>
  )
}

export default OldSalt
